alerting:
  github:
    token: "<github-token>"
    repository-owner: "desxtra"
    repository-name: "devops-jatim-25"
    send-on-resolved: true
    failure-threshold: 3
    success-threshold: 5

endpoints:
  - name: "leantime"
    url: "http://lks-oss-lb-38303394.us-east-1.elb.amazonaws.com"
    interval: 30s
    conditions: 
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 300"
    alerts:
      - type: github
        description: "Sensei, Leantime is down! Please check and fix it."
        enabled: true

  - name: "gatus"
    url: "http://lks-oss-lb-38303394.us-east-1.elb.amazonaws.com:8080"
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 500"
    alerts:
      - type: github
        description: "Sensei, Gatus is down! Please check and fix it."
        enabled: true