# FILL IN THE MISSING VALUES BELOW
alerting:
  github:
    token: "<github-token>" # WARN: DO NOT CHANGE THIS LINE
    repository-url: "https://github.com/desxtra/devops-jatim-25"
    repository-owner: "desxtra"
    repository-name: "devops-jatim-25"
    send-on-resolved: true
    failure-threshold: 3
    success-threshold: 5

# FILL IN THE MISSING VALUES ABOVE

# FILL IN THE MISSING VALUES BELOW
endpoints:
  - name: "Leantime"
    url: <leantime-url> # WARN: DO NOT CHANGE THIS LINE
    interval: 30s
    conditions: 
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 300"
    alerts:
      - type: github
        description: "Sensei, Leantime is down! Please check and fix it."
        enabled: true
        send-on-resolved: true
        failure-threshold: 3
        success-threshold: 5

  - name: "Gatus"
    url: <gatus-url> # WARN: DO NOT CHANGE THIS LINE
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 500"
    alerts:
      - type: github
        description: "Sensei, Gatus is down! Please check and fix it."
        enabled: true
        send-on-resolved: true
        failure-threshold: 3
        success-threshold: 5